/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.amoro.api;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.20.0)", date = "2025-07-22")
public class ExecutorTaskResult implements org.apache.amoro.shade.thrift.org.apache.thrift.TBase<ExecutorTaskResult, ExecutorTaskResult._Fields>, java.io.Serializable, Cloneable, Comparable<ExecutorTaskResult> {
  private static final org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TStruct("ExecutorTaskResult");

  private static final org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TField PROCESS_ID_FIELD_DESC = new org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TField("processId", org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TField TABLE_ID_FIELD_DESC = new org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TField("tableId", org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TField TABLE_IDENTIFIER_FIELD_DESC = new org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TField("tableIdentifier", org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TType.STRUCT, (short)3);
  private static final org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TField ACTION_FIELD_DESC = new org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TField("action", org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TType.STRING, (short)6);
  private static final org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TField STATUS_FIELD_DESC = new org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TField("status", org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TType.I32, (short)7);
  private static final org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TField RETRY_NUMBER_FIELD_DESC = new org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TField("retryNumber", org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TType.I32, (short)8);
  private static final org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TField TASK_OUTPUT_FIELD_DESC = new org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TField("taskOutput", org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TType.STRING, (short)9);
  private static final org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TField ERROR_MESSAGE_FIELD_DESC = new org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TField("errorMessage", org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TType.STRING, (short)10);
  private static final org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TField SUMMARY_FIELD_DESC = new org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TField("summary", org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TType.MAP, (short)11);

  private static final org.apache.amoro.shade.thrift.org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ExecutorTaskResultStandardSchemeFactory();
  private static final org.apache.amoro.shade.thrift.org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ExecutorTaskResultTupleSchemeFactory();

  public long processId; // required
  public long tableId; // required
  public @org.apache.amoro.shade.thrift.org.apache.thrift.annotation.Nullable org.apache.amoro.api.TableIdentifier tableIdentifier; // required
  public @org.apache.amoro.shade.thrift.org.apache.thrift.annotation.Nullable java.lang.String action; // required
  public int status; // required
  public int retryNumber; // required
  public @org.apache.amoro.shade.thrift.org.apache.thrift.annotation.Nullable java.nio.ByteBuffer taskOutput; // optional
  public @org.apache.amoro.shade.thrift.org.apache.thrift.annotation.Nullable java.lang.String errorMessage; // optional
  public @org.apache.amoro.shade.thrift.org.apache.thrift.annotation.Nullable java.util.Map<java.lang.String,java.lang.String> summary; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.amoro.shade.thrift.org.apache.thrift.TFieldIdEnum {
    PROCESS_ID((short)1, "processId"),
    TABLE_ID((short)2, "tableId"),
    TABLE_IDENTIFIER((short)3, "tableIdentifier"),
    ACTION((short)6, "action"),
    STATUS((short)7, "status"),
    RETRY_NUMBER((short)8, "retryNumber"),
    TASK_OUTPUT((short)9, "taskOutput"),
    ERROR_MESSAGE((short)10, "errorMessage"),
    SUMMARY((short)11, "summary");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.amoro.shade.thrift.org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PROCESS_ID
          return PROCESS_ID;
        case 2: // TABLE_ID
          return TABLE_ID;
        case 3: // TABLE_IDENTIFIER
          return TABLE_IDENTIFIER;
        case 6: // ACTION
          return ACTION;
        case 7: // STATUS
          return STATUS;
        case 8: // RETRY_NUMBER
          return RETRY_NUMBER;
        case 9: // TASK_OUTPUT
          return TASK_OUTPUT;
        case 10: // ERROR_MESSAGE
          return ERROR_MESSAGE;
        case 11: // SUMMARY
          return SUMMARY;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.amoro.shade.thrift.org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PROCESSID_ISSET_ID = 0;
  private static final int __TABLEID_ISSET_ID = 1;
  private static final int __STATUS_ISSET_ID = 2;
  private static final int __RETRYNUMBER_ISSET_ID = 3;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.TASK_OUTPUT,_Fields.ERROR_MESSAGE,_Fields.SUMMARY};
  public static final java.util.Map<_Fields, org.apache.amoro.shade.thrift.org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.amoro.shade.thrift.org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.amoro.shade.thrift.org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PROCESS_ID, new org.apache.amoro.shade.thrift.org.apache.thrift.meta_data.FieldMetaData("processId", org.apache.amoro.shade.thrift.org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.amoro.shade.thrift.org.apache.thrift.meta_data.FieldValueMetaData(org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.TABLE_ID, new org.apache.amoro.shade.thrift.org.apache.thrift.meta_data.FieldMetaData("tableId", org.apache.amoro.shade.thrift.org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.amoro.shade.thrift.org.apache.thrift.meta_data.FieldValueMetaData(org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.TABLE_IDENTIFIER, new org.apache.amoro.shade.thrift.org.apache.thrift.meta_data.FieldMetaData("tableIdentifier", org.apache.amoro.shade.thrift.org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.amoro.shade.thrift.org.apache.thrift.meta_data.StructMetaData(org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TType.STRUCT, org.apache.amoro.api.TableIdentifier.class)));
    tmpMap.put(_Fields.ACTION, new org.apache.amoro.shade.thrift.org.apache.thrift.meta_data.FieldMetaData("action", org.apache.amoro.shade.thrift.org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.amoro.shade.thrift.org.apache.thrift.meta_data.FieldValueMetaData(org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.STATUS, new org.apache.amoro.shade.thrift.org.apache.thrift.meta_data.FieldMetaData("status", org.apache.amoro.shade.thrift.org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.amoro.shade.thrift.org.apache.thrift.meta_data.FieldValueMetaData(org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.RETRY_NUMBER, new org.apache.amoro.shade.thrift.org.apache.thrift.meta_data.FieldMetaData("retryNumber", org.apache.amoro.shade.thrift.org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.amoro.shade.thrift.org.apache.thrift.meta_data.FieldValueMetaData(org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.TASK_OUTPUT, new org.apache.amoro.shade.thrift.org.apache.thrift.meta_data.FieldMetaData("taskOutput", org.apache.amoro.shade.thrift.org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.amoro.shade.thrift.org.apache.thrift.meta_data.FieldValueMetaData(org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.ERROR_MESSAGE, new org.apache.amoro.shade.thrift.org.apache.thrift.meta_data.FieldMetaData("errorMessage", org.apache.amoro.shade.thrift.org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.amoro.shade.thrift.org.apache.thrift.meta_data.FieldValueMetaData(org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SUMMARY, new org.apache.amoro.shade.thrift.org.apache.thrift.meta_data.FieldMetaData("summary", org.apache.amoro.shade.thrift.org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.amoro.shade.thrift.org.apache.thrift.meta_data.MapMetaData(org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TType.MAP, 
            new org.apache.amoro.shade.thrift.org.apache.thrift.meta_data.FieldValueMetaData(org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TType.STRING), 
            new org.apache.amoro.shade.thrift.org.apache.thrift.meta_data.FieldValueMetaData(org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.amoro.shade.thrift.org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ExecutorTaskResult.class, metaDataMap);
  }

  public ExecutorTaskResult() {
  }

  public ExecutorTaskResult(
    long processId,
    long tableId,
    org.apache.amoro.api.TableIdentifier tableIdentifier,
    java.lang.String action,
    int status,
    int retryNumber)
  {
    this();
    this.processId = processId;
    setProcessIdIsSet(true);
    this.tableId = tableId;
    setTableIdIsSet(true);
    this.tableIdentifier = tableIdentifier;
    this.action = action;
    this.status = status;
    setStatusIsSet(true);
    this.retryNumber = retryNumber;
    setRetryNumberIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ExecutorTaskResult(ExecutorTaskResult other) {
    __isset_bitfield = other.__isset_bitfield;
    this.processId = other.processId;
    this.tableId = other.tableId;
    if (other.isSetTableIdentifier()) {
      this.tableIdentifier = new org.apache.amoro.api.TableIdentifier(other.tableIdentifier);
    }
    if (other.isSetAction()) {
      this.action = other.action;
    }
    this.status = other.status;
    this.retryNumber = other.retryNumber;
    if (other.isSetTaskOutput()) {
      this.taskOutput = org.apache.amoro.shade.thrift.org.apache.thrift.TBaseHelper.copyBinary(other.taskOutput);
    }
    if (other.isSetErrorMessage()) {
      this.errorMessage = other.errorMessage;
    }
    if (other.isSetSummary()) {
      java.util.Map<java.lang.String,java.lang.String> __this__summary = new java.util.HashMap<java.lang.String,java.lang.String>(other.summary);
      this.summary = __this__summary;
    }
  }

  @Override
  public ExecutorTaskResult deepCopy() {
    return new ExecutorTaskResult(this);
  }

  @Override
  public void clear() {
    setProcessIdIsSet(false);
    this.processId = 0;
    setTableIdIsSet(false);
    this.tableId = 0;
    this.tableIdentifier = null;
    this.action = null;
    setStatusIsSet(false);
    this.status = 0;
    setRetryNumberIsSet(false);
    this.retryNumber = 0;
    this.taskOutput = null;
    this.errorMessage = null;
    this.summary = null;
  }

  public long getProcessId() {
    return this.processId;
  }

  public ExecutorTaskResult setProcessId(long processId) {
    this.processId = processId;
    setProcessIdIsSet(true);
    return this;
  }

  public void unsetProcessId() {
    __isset_bitfield = org.apache.amoro.shade.thrift.org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __PROCESSID_ISSET_ID);
  }

  /** Returns true if field processId is set (has been assigned a value) and false otherwise */
  public boolean isSetProcessId() {
    return org.apache.amoro.shade.thrift.org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __PROCESSID_ISSET_ID);
  }

  public void setProcessIdIsSet(boolean value) {
    __isset_bitfield = org.apache.amoro.shade.thrift.org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __PROCESSID_ISSET_ID, value);
  }

  public long getTableId() {
    return this.tableId;
  }

  public ExecutorTaskResult setTableId(long tableId) {
    this.tableId = tableId;
    setTableIdIsSet(true);
    return this;
  }

  public void unsetTableId() {
    __isset_bitfield = org.apache.amoro.shade.thrift.org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TABLEID_ISSET_ID);
  }

  /** Returns true if field tableId is set (has been assigned a value) and false otherwise */
  public boolean isSetTableId() {
    return org.apache.amoro.shade.thrift.org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TABLEID_ISSET_ID);
  }

  public void setTableIdIsSet(boolean value) {
    __isset_bitfield = org.apache.amoro.shade.thrift.org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TABLEID_ISSET_ID, value);
  }

  @org.apache.amoro.shade.thrift.org.apache.thrift.annotation.Nullable
  public org.apache.amoro.api.TableIdentifier getTableIdentifier() {
    return this.tableIdentifier;
  }

  public ExecutorTaskResult setTableIdentifier(@org.apache.amoro.shade.thrift.org.apache.thrift.annotation.Nullable org.apache.amoro.api.TableIdentifier tableIdentifier) {
    this.tableIdentifier = tableIdentifier;
    return this;
  }

  public void unsetTableIdentifier() {
    this.tableIdentifier = null;
  }

  /** Returns true if field tableIdentifier is set (has been assigned a value) and false otherwise */
  public boolean isSetTableIdentifier() {
    return this.tableIdentifier != null;
  }

  public void setTableIdentifierIsSet(boolean value) {
    if (!value) {
      this.tableIdentifier = null;
    }
  }

  @org.apache.amoro.shade.thrift.org.apache.thrift.annotation.Nullable
  public java.lang.String getAction() {
    return this.action;
  }

  public ExecutorTaskResult setAction(@org.apache.amoro.shade.thrift.org.apache.thrift.annotation.Nullable java.lang.String action) {
    this.action = action;
    return this;
  }

  public void unsetAction() {
    this.action = null;
  }

  /** Returns true if field action is set (has been assigned a value) and false otherwise */
  public boolean isSetAction() {
    return this.action != null;
  }

  public void setActionIsSet(boolean value) {
    if (!value) {
      this.action = null;
    }
  }

  public int getStatus() {
    return this.status;
  }

  public ExecutorTaskResult setStatus(int status) {
    this.status = status;
    setStatusIsSet(true);
    return this;
  }

  public void unsetStatus() {
    __isset_bitfield = org.apache.amoro.shade.thrift.org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __STATUS_ISSET_ID);
  }

  /** Returns true if field status is set (has been assigned a value) and false otherwise */
  public boolean isSetStatus() {
    return org.apache.amoro.shade.thrift.org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __STATUS_ISSET_ID);
  }

  public void setStatusIsSet(boolean value) {
    __isset_bitfield = org.apache.amoro.shade.thrift.org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __STATUS_ISSET_ID, value);
  }

  public int getRetryNumber() {
    return this.retryNumber;
  }

  public ExecutorTaskResult setRetryNumber(int retryNumber) {
    this.retryNumber = retryNumber;
    setRetryNumberIsSet(true);
    return this;
  }

  public void unsetRetryNumber() {
    __isset_bitfield = org.apache.amoro.shade.thrift.org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __RETRYNUMBER_ISSET_ID);
  }

  /** Returns true if field retryNumber is set (has been assigned a value) and false otherwise */
  public boolean isSetRetryNumber() {
    return org.apache.amoro.shade.thrift.org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __RETRYNUMBER_ISSET_ID);
  }

  public void setRetryNumberIsSet(boolean value) {
    __isset_bitfield = org.apache.amoro.shade.thrift.org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __RETRYNUMBER_ISSET_ID, value);
  }

  public byte[] getTaskOutput() {
    setTaskOutput(org.apache.amoro.shade.thrift.org.apache.thrift.TBaseHelper.rightSize(taskOutput));
    return taskOutput == null ? null : taskOutput.array();
  }

  public java.nio.ByteBuffer bufferForTaskOutput() {
    return org.apache.amoro.shade.thrift.org.apache.thrift.TBaseHelper.copyBinary(taskOutput);
  }

  public ExecutorTaskResult setTaskOutput(byte[] taskOutput) {
    this.taskOutput = taskOutput == null ? (java.nio.ByteBuffer)null   : java.nio.ByteBuffer.wrap(taskOutput.clone());
    return this;
  }

  public ExecutorTaskResult setTaskOutput(@org.apache.amoro.shade.thrift.org.apache.thrift.annotation.Nullable java.nio.ByteBuffer taskOutput) {
    this.taskOutput = org.apache.amoro.shade.thrift.org.apache.thrift.TBaseHelper.copyBinary(taskOutput);
    return this;
  }

  public void unsetTaskOutput() {
    this.taskOutput = null;
  }

  /** Returns true if field taskOutput is set (has been assigned a value) and false otherwise */
  public boolean isSetTaskOutput() {
    return this.taskOutput != null;
  }

  public void setTaskOutputIsSet(boolean value) {
    if (!value) {
      this.taskOutput = null;
    }
  }

  @org.apache.amoro.shade.thrift.org.apache.thrift.annotation.Nullable
  public java.lang.String getErrorMessage() {
    return this.errorMessage;
  }

  public ExecutorTaskResult setErrorMessage(@org.apache.amoro.shade.thrift.org.apache.thrift.annotation.Nullable java.lang.String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

  public void unsetErrorMessage() {
    this.errorMessage = null;
  }

  /** Returns true if field errorMessage is set (has been assigned a value) and false otherwise */
  public boolean isSetErrorMessage() {
    return this.errorMessage != null;
  }

  public void setErrorMessageIsSet(boolean value) {
    if (!value) {
      this.errorMessage = null;
    }
  }

  public int getSummarySize() {
    return (this.summary == null) ? 0 : this.summary.size();
  }

  public void putToSummary(java.lang.String key, java.lang.String val) {
    if (this.summary == null) {
      this.summary = new java.util.HashMap<java.lang.String,java.lang.String>();
    }
    this.summary.put(key, val);
  }

  @org.apache.amoro.shade.thrift.org.apache.thrift.annotation.Nullable
  public java.util.Map<java.lang.String,java.lang.String> getSummary() {
    return this.summary;
  }

  public ExecutorTaskResult setSummary(@org.apache.amoro.shade.thrift.org.apache.thrift.annotation.Nullable java.util.Map<java.lang.String,java.lang.String> summary) {
    this.summary = summary;
    return this;
  }

  public void unsetSummary() {
    this.summary = null;
  }

  /** Returns true if field summary is set (has been assigned a value) and false otherwise */
  public boolean isSetSummary() {
    return this.summary != null;
  }

  public void setSummaryIsSet(boolean value) {
    if (!value) {
      this.summary = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.amoro.shade.thrift.org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case PROCESS_ID:
      if (value == null) {
        unsetProcessId();
      } else {
        setProcessId((java.lang.Long)value);
      }
      break;

    case TABLE_ID:
      if (value == null) {
        unsetTableId();
      } else {
        setTableId((java.lang.Long)value);
      }
      break;

    case TABLE_IDENTIFIER:
      if (value == null) {
        unsetTableIdentifier();
      } else {
        setTableIdentifier((org.apache.amoro.api.TableIdentifier)value);
      }
      break;

    case ACTION:
      if (value == null) {
        unsetAction();
      } else {
        setAction((java.lang.String)value);
      }
      break;

    case STATUS:
      if (value == null) {
        unsetStatus();
      } else {
        setStatus((java.lang.Integer)value);
      }
      break;

    case RETRY_NUMBER:
      if (value == null) {
        unsetRetryNumber();
      } else {
        setRetryNumber((java.lang.Integer)value);
      }
      break;

    case TASK_OUTPUT:
      if (value == null) {
        unsetTaskOutput();
      } else {
        if (value instanceof byte[]) {
          setTaskOutput((byte[])value);
        } else {
          setTaskOutput((java.nio.ByteBuffer)value);
        }
      }
      break;

    case ERROR_MESSAGE:
      if (value == null) {
        unsetErrorMessage();
      } else {
        setErrorMessage((java.lang.String)value);
      }
      break;

    case SUMMARY:
      if (value == null) {
        unsetSummary();
      } else {
        setSummary((java.util.Map<java.lang.String,java.lang.String>)value);
      }
      break;

    }
  }

  @org.apache.amoro.shade.thrift.org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case PROCESS_ID:
      return getProcessId();

    case TABLE_ID:
      return getTableId();

    case TABLE_IDENTIFIER:
      return getTableIdentifier();

    case ACTION:
      return getAction();

    case STATUS:
      return getStatus();

    case RETRY_NUMBER:
      return getRetryNumber();

    case TASK_OUTPUT:
      return getTaskOutput();

    case ERROR_MESSAGE:
      return getErrorMessage();

    case SUMMARY:
      return getSummary();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case PROCESS_ID:
      return isSetProcessId();
    case TABLE_ID:
      return isSetTableId();
    case TABLE_IDENTIFIER:
      return isSetTableIdentifier();
    case ACTION:
      return isSetAction();
    case STATUS:
      return isSetStatus();
    case RETRY_NUMBER:
      return isSetRetryNumber();
    case TASK_OUTPUT:
      return isSetTaskOutput();
    case ERROR_MESSAGE:
      return isSetErrorMessage();
    case SUMMARY:
      return isSetSummary();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof ExecutorTaskResult)
      return this.equals((ExecutorTaskResult)that);
    return false;
  }

  public boolean equals(ExecutorTaskResult that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_processId = true;
    boolean that_present_processId = true;
    if (this_present_processId || that_present_processId) {
      if (!(this_present_processId && that_present_processId))
        return false;
      if (this.processId != that.processId)
        return false;
    }

    boolean this_present_tableId = true;
    boolean that_present_tableId = true;
    if (this_present_tableId || that_present_tableId) {
      if (!(this_present_tableId && that_present_tableId))
        return false;
      if (this.tableId != that.tableId)
        return false;
    }

    boolean this_present_tableIdentifier = true && this.isSetTableIdentifier();
    boolean that_present_tableIdentifier = true && that.isSetTableIdentifier();
    if (this_present_tableIdentifier || that_present_tableIdentifier) {
      if (!(this_present_tableIdentifier && that_present_tableIdentifier))
        return false;
      if (!this.tableIdentifier.equals(that.tableIdentifier))
        return false;
    }

    boolean this_present_action = true && this.isSetAction();
    boolean that_present_action = true && that.isSetAction();
    if (this_present_action || that_present_action) {
      if (!(this_present_action && that_present_action))
        return false;
      if (!this.action.equals(that.action))
        return false;
    }

    boolean this_present_status = true;
    boolean that_present_status = true;
    if (this_present_status || that_present_status) {
      if (!(this_present_status && that_present_status))
        return false;
      if (this.status != that.status)
        return false;
    }

    boolean this_present_retryNumber = true;
    boolean that_present_retryNumber = true;
    if (this_present_retryNumber || that_present_retryNumber) {
      if (!(this_present_retryNumber && that_present_retryNumber))
        return false;
      if (this.retryNumber != that.retryNumber)
        return false;
    }

    boolean this_present_taskOutput = true && this.isSetTaskOutput();
    boolean that_present_taskOutput = true && that.isSetTaskOutput();
    if (this_present_taskOutput || that_present_taskOutput) {
      if (!(this_present_taskOutput && that_present_taskOutput))
        return false;
      if (!this.taskOutput.equals(that.taskOutput))
        return false;
    }

    boolean this_present_errorMessage = true && this.isSetErrorMessage();
    boolean that_present_errorMessage = true && that.isSetErrorMessage();
    if (this_present_errorMessage || that_present_errorMessage) {
      if (!(this_present_errorMessage && that_present_errorMessage))
        return false;
      if (!this.errorMessage.equals(that.errorMessage))
        return false;
    }

    boolean this_present_summary = true && this.isSetSummary();
    boolean that_present_summary = true && that.isSetSummary();
    if (this_present_summary || that_present_summary) {
      if (!(this_present_summary && that_present_summary))
        return false;
      if (!this.summary.equals(that.summary))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.amoro.shade.thrift.org.apache.thrift.TBaseHelper.hashCode(processId);

    hashCode = hashCode * 8191 + org.apache.amoro.shade.thrift.org.apache.thrift.TBaseHelper.hashCode(tableId);

    hashCode = hashCode * 8191 + ((isSetTableIdentifier()) ? 131071 : 524287);
    if (isSetTableIdentifier())
      hashCode = hashCode * 8191 + tableIdentifier.hashCode();

    hashCode = hashCode * 8191 + ((isSetAction()) ? 131071 : 524287);
    if (isSetAction())
      hashCode = hashCode * 8191 + action.hashCode();

    hashCode = hashCode * 8191 + status;

    hashCode = hashCode * 8191 + retryNumber;

    hashCode = hashCode * 8191 + ((isSetTaskOutput()) ? 131071 : 524287);
    if (isSetTaskOutput())
      hashCode = hashCode * 8191 + taskOutput.hashCode();

    hashCode = hashCode * 8191 + ((isSetErrorMessage()) ? 131071 : 524287);
    if (isSetErrorMessage())
      hashCode = hashCode * 8191 + errorMessage.hashCode();

    hashCode = hashCode * 8191 + ((isSetSummary()) ? 131071 : 524287);
    if (isSetSummary())
      hashCode = hashCode * 8191 + summary.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(ExecutorTaskResult other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetProcessId(), other.isSetProcessId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProcessId()) {
      lastComparison = org.apache.amoro.shade.thrift.org.apache.thrift.TBaseHelper.compareTo(this.processId, other.processId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetTableId(), other.isSetTableId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTableId()) {
      lastComparison = org.apache.amoro.shade.thrift.org.apache.thrift.TBaseHelper.compareTo(this.tableId, other.tableId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetTableIdentifier(), other.isSetTableIdentifier());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTableIdentifier()) {
      lastComparison = org.apache.amoro.shade.thrift.org.apache.thrift.TBaseHelper.compareTo(this.tableIdentifier, other.tableIdentifier);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetAction(), other.isSetAction());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAction()) {
      lastComparison = org.apache.amoro.shade.thrift.org.apache.thrift.TBaseHelper.compareTo(this.action, other.action);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetStatus(), other.isSetStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStatus()) {
      lastComparison = org.apache.amoro.shade.thrift.org.apache.thrift.TBaseHelper.compareTo(this.status, other.status);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetRetryNumber(), other.isSetRetryNumber());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRetryNumber()) {
      lastComparison = org.apache.amoro.shade.thrift.org.apache.thrift.TBaseHelper.compareTo(this.retryNumber, other.retryNumber);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetTaskOutput(), other.isSetTaskOutput());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTaskOutput()) {
      lastComparison = org.apache.amoro.shade.thrift.org.apache.thrift.TBaseHelper.compareTo(this.taskOutput, other.taskOutput);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetErrorMessage(), other.isSetErrorMessage());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetErrorMessage()) {
      lastComparison = org.apache.amoro.shade.thrift.org.apache.thrift.TBaseHelper.compareTo(this.errorMessage, other.errorMessage);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetSummary(), other.isSetSummary());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSummary()) {
      lastComparison = org.apache.amoro.shade.thrift.org.apache.thrift.TBaseHelper.compareTo(this.summary, other.summary);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.amoro.shade.thrift.org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TProtocol iprot) throws org.apache.amoro.shade.thrift.org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TProtocol oprot) throws org.apache.amoro.shade.thrift.org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("ExecutorTaskResult(");
    boolean first = true;

    sb.append("processId:");
    sb.append(this.processId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("tableId:");
    sb.append(this.tableId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("tableIdentifier:");
    if (this.tableIdentifier == null) {
      sb.append("null");
    } else {
      sb.append(this.tableIdentifier);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("action:");
    if (this.action == null) {
      sb.append("null");
    } else {
      sb.append(this.action);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("status:");
    sb.append(this.status);
    first = false;
    if (!first) sb.append(", ");
    sb.append("retryNumber:");
    sb.append(this.retryNumber);
    first = false;
    if (isSetTaskOutput()) {
      if (!first) sb.append(", ");
      sb.append("taskOutput:");
      if (this.taskOutput == null) {
        sb.append("null");
      } else {
        org.apache.amoro.shade.thrift.org.apache.thrift.TBaseHelper.toString(this.taskOutput, sb);
      }
      first = false;
    }
    if (isSetErrorMessage()) {
      if (!first) sb.append(", ");
      sb.append("errorMessage:");
      if (this.errorMessage == null) {
        sb.append("null");
      } else {
        sb.append(this.errorMessage);
      }
      first = false;
    }
    if (isSetSummary()) {
      if (!first) sb.append(", ");
      sb.append("summary:");
      if (this.summary == null) {
        sb.append("null");
      } else {
        sb.append(this.summary);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.amoro.shade.thrift.org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (tableIdentifier != null) {
      tableIdentifier.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TCompactProtocol(new org.apache.amoro.shade.thrift.org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.amoro.shade.thrift.org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TCompactProtocol(new org.apache.amoro.shade.thrift.org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.amoro.shade.thrift.org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ExecutorTaskResultStandardSchemeFactory implements org.apache.amoro.shade.thrift.org.apache.thrift.scheme.SchemeFactory {
    @Override
    public ExecutorTaskResultStandardScheme getScheme() {
      return new ExecutorTaskResultStandardScheme();
    }
  }

  private static class ExecutorTaskResultStandardScheme extends org.apache.amoro.shade.thrift.org.apache.thrift.scheme.StandardScheme<ExecutorTaskResult> {

    @Override
    public void read(org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TProtocol iprot, ExecutorTaskResult struct) throws org.apache.amoro.shade.thrift.org.apache.thrift.TException {
      org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PROCESS_ID
            if (schemeField.type == org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TType.I64) {
              struct.processId = iprot.readI64();
              struct.setProcessIdIsSet(true);
            } else { 
              org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TABLE_ID
            if (schemeField.type == org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TType.I64) {
              struct.tableId = iprot.readI64();
              struct.setTableIdIsSet(true);
            } else { 
              org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // TABLE_IDENTIFIER
            if (schemeField.type == org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TType.STRUCT) {
              struct.tableIdentifier = new org.apache.amoro.api.TableIdentifier();
              struct.tableIdentifier.read(iprot);
              struct.setTableIdentifierIsSet(true);
            } else { 
              org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // ACTION
            if (schemeField.type == org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TType.STRING) {
              struct.action = iprot.readString();
              struct.setActionIsSet(true);
            } else { 
              org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // STATUS
            if (schemeField.type == org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TType.I32) {
              struct.status = iprot.readI32();
              struct.setStatusIsSet(true);
            } else { 
              org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // RETRY_NUMBER
            if (schemeField.type == org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TType.I32) {
              struct.retryNumber = iprot.readI32();
              struct.setRetryNumberIsSet(true);
            } else { 
              org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // TASK_OUTPUT
            if (schemeField.type == org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TType.STRING) {
              struct.taskOutput = iprot.readBinary();
              struct.setTaskOutputIsSet(true);
            } else { 
              org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // ERROR_MESSAGE
            if (schemeField.type == org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TType.STRING) {
              struct.errorMessage = iprot.readString();
              struct.setErrorMessageIsSet(true);
            } else { 
              org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // SUMMARY
            if (schemeField.type == org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TMap _map0 = iprot.readMapBegin();
                struct.summary = new java.util.HashMap<java.lang.String,java.lang.String>(2*_map0.size);
                @org.apache.amoro.shade.thrift.org.apache.thrift.annotation.Nullable java.lang.String _key1;
                @org.apache.amoro.shade.thrift.org.apache.thrift.annotation.Nullable java.lang.String _val2;
                for (int _i3 = 0; _i3 < _map0.size; ++_i3)
                {
                  _key1 = iprot.readString();
                  _val2 = iprot.readString();
                  struct.summary.put(_key1, _val2);
                }
                iprot.readMapEnd();
              }
              struct.setSummaryIsSet(true);
            } else { 
              org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TProtocol oprot, ExecutorTaskResult struct) throws org.apache.amoro.shade.thrift.org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(PROCESS_ID_FIELD_DESC);
      oprot.writeI64(struct.processId);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(TABLE_ID_FIELD_DESC);
      oprot.writeI64(struct.tableId);
      oprot.writeFieldEnd();
      if (struct.tableIdentifier != null) {
        oprot.writeFieldBegin(TABLE_IDENTIFIER_FIELD_DESC);
        struct.tableIdentifier.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.action != null) {
        oprot.writeFieldBegin(ACTION_FIELD_DESC);
        oprot.writeString(struct.action);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(STATUS_FIELD_DESC);
      oprot.writeI32(struct.status);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(RETRY_NUMBER_FIELD_DESC);
      oprot.writeI32(struct.retryNumber);
      oprot.writeFieldEnd();
      if (struct.taskOutput != null) {
        if (struct.isSetTaskOutput()) {
          oprot.writeFieldBegin(TASK_OUTPUT_FIELD_DESC);
          oprot.writeBinary(struct.taskOutput);
          oprot.writeFieldEnd();
        }
      }
      if (struct.errorMessage != null) {
        if (struct.isSetErrorMessage()) {
          oprot.writeFieldBegin(ERROR_MESSAGE_FIELD_DESC);
          oprot.writeString(struct.errorMessage);
          oprot.writeFieldEnd();
        }
      }
      if (struct.summary != null) {
        if (struct.isSetSummary()) {
          oprot.writeFieldBegin(SUMMARY_FIELD_DESC);
          {
            oprot.writeMapBegin(new org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TMap(org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TType.STRING, org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TType.STRING, struct.summary.size()));
            for (java.util.Map.Entry<java.lang.String, java.lang.String> _iter4 : struct.summary.entrySet())
            {
              oprot.writeString(_iter4.getKey());
              oprot.writeString(_iter4.getValue());
            }
            oprot.writeMapEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ExecutorTaskResultTupleSchemeFactory implements org.apache.amoro.shade.thrift.org.apache.thrift.scheme.SchemeFactory {
    @Override
    public ExecutorTaskResultTupleScheme getScheme() {
      return new ExecutorTaskResultTupleScheme();
    }
  }

  private static class ExecutorTaskResultTupleScheme extends org.apache.amoro.shade.thrift.org.apache.thrift.scheme.TupleScheme<ExecutorTaskResult> {

    @Override
    public void write(org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TProtocol prot, ExecutorTaskResult struct) throws org.apache.amoro.shade.thrift.org.apache.thrift.TException {
      org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetProcessId()) {
        optionals.set(0);
      }
      if (struct.isSetTableId()) {
        optionals.set(1);
      }
      if (struct.isSetTableIdentifier()) {
        optionals.set(2);
      }
      if (struct.isSetAction()) {
        optionals.set(3);
      }
      if (struct.isSetStatus()) {
        optionals.set(4);
      }
      if (struct.isSetRetryNumber()) {
        optionals.set(5);
      }
      if (struct.isSetTaskOutput()) {
        optionals.set(6);
      }
      if (struct.isSetErrorMessage()) {
        optionals.set(7);
      }
      if (struct.isSetSummary()) {
        optionals.set(8);
      }
      oprot.writeBitSet(optionals, 9);
      if (struct.isSetProcessId()) {
        oprot.writeI64(struct.processId);
      }
      if (struct.isSetTableId()) {
        oprot.writeI64(struct.tableId);
      }
      if (struct.isSetTableIdentifier()) {
        struct.tableIdentifier.write(oprot);
      }
      if (struct.isSetAction()) {
        oprot.writeString(struct.action);
      }
      if (struct.isSetStatus()) {
        oprot.writeI32(struct.status);
      }
      if (struct.isSetRetryNumber()) {
        oprot.writeI32(struct.retryNumber);
      }
      if (struct.isSetTaskOutput()) {
        oprot.writeBinary(struct.taskOutput);
      }
      if (struct.isSetErrorMessage()) {
        oprot.writeString(struct.errorMessage);
      }
      if (struct.isSetSummary()) {
        {
          oprot.writeI32(struct.summary.size());
          for (java.util.Map.Entry<java.lang.String, java.lang.String> _iter5 : struct.summary.entrySet())
          {
            oprot.writeString(_iter5.getKey());
            oprot.writeString(_iter5.getValue());
          }
        }
      }
    }

    @Override
    public void read(org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TProtocol prot, ExecutorTaskResult struct) throws org.apache.amoro.shade.thrift.org.apache.thrift.TException {
      org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(9);
      if (incoming.get(0)) {
        struct.processId = iprot.readI64();
        struct.setProcessIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.tableId = iprot.readI64();
        struct.setTableIdIsSet(true);
      }
      if (incoming.get(2)) {
        struct.tableIdentifier = new org.apache.amoro.api.TableIdentifier();
        struct.tableIdentifier.read(iprot);
        struct.setTableIdentifierIsSet(true);
      }
      if (incoming.get(3)) {
        struct.action = iprot.readString();
        struct.setActionIsSet(true);
      }
      if (incoming.get(4)) {
        struct.status = iprot.readI32();
        struct.setStatusIsSet(true);
      }
      if (incoming.get(5)) {
        struct.retryNumber = iprot.readI32();
        struct.setRetryNumberIsSet(true);
      }
      if (incoming.get(6)) {
        struct.taskOutput = iprot.readBinary();
        struct.setTaskOutputIsSet(true);
      }
      if (incoming.get(7)) {
        struct.errorMessage = iprot.readString();
        struct.setErrorMessageIsSet(true);
      }
      if (incoming.get(8)) {
        {
          org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TMap _map6 = iprot.readMapBegin(org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TType.STRING, org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TType.STRING); 
          struct.summary = new java.util.HashMap<java.lang.String,java.lang.String>(2*_map6.size);
          @org.apache.amoro.shade.thrift.org.apache.thrift.annotation.Nullable java.lang.String _key7;
          @org.apache.amoro.shade.thrift.org.apache.thrift.annotation.Nullable java.lang.String _val8;
          for (int _i9 = 0; _i9 < _map6.size; ++_i9)
          {
            _key7 = iprot.readString();
            _val8 = iprot.readString();
            struct.summary.put(_key7, _val8);
          }
        }
        struct.setSummaryIsSet(true);
      }
    }
  }

  private static <S extends org.apache.amoro.shade.thrift.org.apache.thrift.scheme.IScheme> S scheme(org.apache.amoro.shade.thrift.org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.amoro.shade.thrift.org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

